//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Positive.Model.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Stock {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Stock() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleArch.Model.Languages.Stock", typeof(Stock).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt Dizin Ekle.
        /// </summary>
        public static string AddChild {
            get {
                return ResourceManager.GetString("AddChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Dizin Ekle.
        /// </summary>
        public static string AddRoot {
            get {
                return ResourceManager.GetString("AddRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Ekle.
        /// </summary>
        public static string AddStock {
            get {
                return ResourceManager.GetString("AddStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Kodu.
        /// </summary>
        public static string CatalogCode {
            get {
                return ResourceManager.GetString("CatalogCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog.
        /// </summary>
        public static string CatalogId {
            get {
                return ResourceManager.GetString("CatalogId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Kodu.
        /// </summary>
        public static string CatgoryCode {
            get {
                return ResourceManager.GetString("CatgoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod Index.
        /// </summary>
        public static string CodeIndex {
            get {
                return ResourceManager.GetString("CodeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Kod.
        /// </summary>
        public static string CompleteKey {
            get {
                return ResourceManager.GetString("CompleteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanım.
        /// </summary>
        public static string Definition {
            get {
                return ResourceManager.GetString("Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanım.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büyük İmage.
        /// </summary>
        public static string LargeImage {
            get {
                return ResourceManager.GetString("LargeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üst Kod.
        /// </summary>
        public static string ParentId {
            get {
                return ResourceManager.GetString("ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adet.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Küçük İmaj.
        /// </summary>
        public static string SmallImage {
            get {
                return ResourceManager.GetString("SmallImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Kod.
        /// </summary>
        public static string SmartCode {
            get {
                return ResourceManager.GetString("SmartCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok.
        /// </summary>
        public static string StockId {
            get {
                return ResourceManager.GetString("StockId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büyük Stok Resmi.
        /// </summary>
        public static string StockImageLarge {
            get {
                return ResourceManager.GetString("StockImageLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Küçük Stok Resmi.
        /// </summary>
        public static string StockImageSmall {
            get {
                return ResourceManager.GetString("StockImageSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Adı.
        /// </summary>
        public static string StockName {
            get {
                return ResourceManager.GetString("StockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birim.
        /// </summary>
        public static string StockUnitId {
            get {
                return ResourceManager.GetString("StockUnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedarikçi.
        /// </summary>
        public static string SupplierId {
            get {
                return ResourceManager.GetString("SupplierId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedarikçi.
        /// </summary>
        public static string SupplierName {
            get {
                return ResourceManager.GetString("SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedarikçi Kodu.
        /// </summary>
        public static string SupplierProductCode {
            get {
                return ResourceManager.GetString("SupplierProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birim.
        /// </summary>
        public static string UnitName {
            get {
                return ResourceManager.GetString("UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Tanımlıdır.
        /// </summary>
        public static string ValCategoryExists {
            get {
                return ResourceManager.GetString("ValCategoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı Firmaya ait tekrar eden ürün Kodu, kod değerini değiştiriniz..
        /// </summary>
        public static string ValFirmProductCode {
            get {
                return ResourceManager.GetString("ValFirmProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı Firmaya ait tekrar eden kod, kod değerini değiştiriniz..
        /// </summary>
        public static string ValFirmSmartCodeExists {
            get {
                return ResourceManager.GetString("ValFirmSmartCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori değeri geçersiz..
        /// </summary>
        public static string ValStockCategory {
            get {
                return ResourceManager.GetString("ValStockCategory", resourceCulture);
            }
        }
    }
}
